name: DragonflyDB Benchmark
on: [push, pull_request]
jobs:
  benchmark:
    runs-on: ubuntu-latest
    services:
      dragonflydb:
        image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
        ports:
          - 6379:6379
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install lcov autoconf automake pkg-config libevent-dev libpcre3-dev libssl-dev

    - name: Build memtier_benchmark
      run: autoreconf -ivf && ./configure --enable-code-coverage && make -j

    - name: Increase connection limit
      run: |
        sudo sysctl -w net.ipv4.tcp_fin_timeout=10
        sudo sysctl -w net.ipv4.tcp_tw_reuse=1
        ulimit -n 40960

    - name: Benchmark
      run:
        cd /home/runner/work/memtier_benchmark/ & ./memtier_benchmark -h localhost -p 6379 --distinct-client-seed --hide-histogram --ratio 1:1 -t 30 -c 10 -n 100000